name: discord_shell
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: Benny Jacobs <email@example.com>

environment:
  sdk: '>=2.0.0-dev.8'

dependencies:
  discord:
    path: 'nyx'

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
